version: '3.8'

services:

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    networks: 
      - net
    volumes:
      - database:/var/lib/mysql
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    restart: always
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_vl:/var/www/html
    networks:
      - net

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    restart: always
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress_vl:/var/www/html 
    networks:
      - net


volumes:
  database:
    name: mariadb_db
    driver_opts:
      type: none 
      device: /home/isidki/data/mariadb
      o: bind
  wordpress_vl:
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device: /home/isidki/data/wordpress


networks:
  net:
    name: net
    driver: bridge
